clf:
  name: SVM
  params:
    C: 0.9
    max_iter: 2000
    kernel: linear

evaluation:
  cv: 5
  metrics:
    - accuracy
    - precision
    - recall
    - f1

files:
  test_data: test_data.csv
  train_data: train_data.csv
  model: pipeline_tfidf_svm.onnx

mlflow:
  uri: http://128.0.1.1:8080

preprocessing:
  name: tfidf
  params:
    max_features: 5000
    min_df: 3

yandexcloud:
  # credentials for project-specific service account with limited viewer rights
  access_key_id: YCAJEOgFvUrPOU1lo3wn6DIeV
  secret_access_key: YCMQO-cnIrAoIoUSMGA9YT2DqZAUmzZY6W8GuROv
